import { v2DbList } from './vanilla2.js';

const artefacts2DbList = [...v2DbList];

const artefacts2LocList = [
  '!!stompies_brt_items_ancillaries__',
  '!!stompies_brt_items_character_skills__',
  '!!stompies_brt_items_effects__',
  '!!stompies_brt_items_unit_abilities__',
  '!!stompies_bst_items_ancillaries__',
  '!!stompies_bst_items_character_skills__',
  '!!stompies_bst_items_effects__',
  '!!stompies_bst_items_unit_abilities__',
  '!!stompies_chs_items_ancillaries__',
  '!!stompies_chs_items_character_skills__',
  '!!stompies_chs_items_effects__',
  '!!stompies_chs_items_unit_abilities__',
  '!!stompies_cst_items_ancillaries__',
  '!!stompies_cst_items_character_skills__',
  '!!stompies_cst_items_effects__',
  '!!stompies_cst_items_unit_abilities__',
  '!!stompies_def_items_ancillaries__',
  '!!stompies_def_items_character_skills__',
  '!!stompies_def_items_effects__',
  '!!stompies_def_items_unit_abilities__',
  '!!stompies_dwf_items_ancillaries__',
  '!!stompies_dwf_items_character_skills__',
  '!!stompies_dwf_items_effects__',
  '!!stompies_dwf_items_unit_abilities__',
  '!!stompies_emp_items_ancillaries__',
  '!!stompies_emp_items_character_skills__',
  '!!stompies_emp_items_effects__',
  '!!stompies_emp_items_unit_abilities__',
  '!!stompies_grn_items_ancillaries__',
  '!!stompies_grn_items_character_skills__',
  '!!stompies_grn_items_effects__',
  '!!stompies_grn_items_unit_abilities__',
  '!!stompies_hef_items_ancillaries__',
  '!!stompies_hef_items_character_skills__',
  '!!stompies_hef_items_effects__',
  '!!stompies_hef_items_unit_abilities__',
  '!!stompies_lzd_items_ancillaries__',
  '!!stompies_lzd_items_character_skills__',
  '!!stompies_lzd_items_effects__',
  '!!stompies_lzd_items_unit_abilities__',
  '!!stompies_nor_items_ancillaries__',
  '!!stompies_nor_items_character_skills__',
  '!!stompies_nor_items_effects__',
  '!!stompies_nor_items_unit_abilities__',
  '!!stompies_skv_items_ancillaries__',
  '!!stompies_skv_items_character_skills__',
  '!!stompies_skv_items_effects__',
  '!!stompies_skv_items_unit_abilities__',
  '!!stompies_tmb_items_ancillaries__',
  '!!stompies_tmb_items_character_skills__',
  '!!stompies_tmb_items_effects__',
  '!!stompies_tmb_items_unit_abilities__',
  '!!stompies_vmp_items_ancillaries__',
  '!!stompies_vmp_items_character_skills__',
  '!!stompies_vmp_items_effects__',
  '!!stompies_vmp_items_unit_abilities__',
  '!!stompies_wef_items_ancillaries__',
  '!!stompies_wef_items_character_skills__',
  '!!stompies_wef_items_effects__',
  '!!stompies_wef_items_unit_abilities__',
  '!!stompies_z_unit_abilities_additional_ui_effects__',
];

const artefacts2LocMap = {
  '!!stompies_brt_items_ancillaries__': 'ancillaries',
  '!!stompies_brt_items_character_skills__': 'character_skills',
  '!!stompies_brt_items_effects__': 'effects',
  '!!stompies_brt_items_unit_abilities__': 'unit_abilities',
  '!!stompies_bst_items_ancillaries__': 'ancillaries',
  '!!stompies_bst_items_character_skills__': 'character_skills',
  '!!stompies_bst_items_effects__': 'effects',
  '!!stompies_bst_items_unit_abilities__': 'unit_abilities',
  '!!stompies_chs_items_ancillaries__': 'ancillaries',
  '!!stompies_chs_items_character_skills__': 'character_skills',
  '!!stompies_chs_items_effects__': 'effects',
  '!!stompies_chs_items_unit_abilities__': 'unit_abilities',
  '!!stompies_cst_items_ancillaries__': 'ancillaries',
  '!!stompies_cst_items_character_skills__': 'character_skills',
  '!!stompies_cst_items_effects__': 'effects',
  '!!stompies_cst_items_unit_abilities__': 'unit_abilities',
  '!!stompies_def_items_ancillaries__': 'ancillaries',
  '!!stompies_def_items_character_skills__': 'character_skills',
  '!!stompies_def_items_effects__': 'effects',
  '!!stompies_def_items_unit_abilities__': 'unit_abilities',
  '!!stompies_dwf_items_ancillaries__': 'ancillaries',
  '!!stompies_dwf_items_character_skills__': 'character_skills',
  '!!stompies_dwf_items_effects__': 'effects',
  '!!stompies_dwf_items_unit_abilities__': 'unit_abilities',
  '!!stompies_emp_items_ancillaries__': 'ancillaries',
  '!!stompies_emp_items_character_skills__': 'character_skills',
  '!!stompies_emp_items_effects__': 'effects',
  '!!stompies_emp_items_unit_abilities__': 'unit_abilities',
  '!!stompies_grn_items_ancillaries__': 'ancillaries',
  '!!stompies_grn_items_character_skills__': 'character_skills',
  '!!stompies_grn_items_effects__': 'effects',
  '!!stompies_grn_items_unit_abilities__': 'unit_abilities',
  '!!stompies_hef_items_ancillaries__': 'ancillaries',
  '!!stompies_hef_items_character_skills__': 'character_skills',
  '!!stompies_hef_items_effects__': 'effects',
  '!!stompies_hef_items_unit_abilities__': 'unit_abilities',
  '!!stompies_lzd_items_ancillaries__': 'ancillaries',
  '!!stompies_lzd_items_character_skills__': 'character_skills',
  '!!stompies_lzd_items_effects__': 'effects',
  '!!stompies_lzd_items_unit_abilities__': 'unit_abilities',
  '!!stompies_nor_items_ancillaries__': 'ancillaries',
  '!!stompies_nor_items_character_skills__': 'character_skills',
  '!!stompies_nor_items_effects__': 'effects',
  '!!stompies_nor_items_unit_abilities__': 'unit_abilities',
  '!!stompies_skv_items_ancillaries__': 'ancillaries',
  '!!stompies_skv_items_character_skills__': 'character_skills',
  '!!stompies_skv_items_effects__': 'effects',
  '!!stompies_skv_items_unit_abilities__': 'unit_abilities',
  '!!stompies_tmb_items_ancillaries__': 'ancillaries',
  '!!stompies_tmb_items_character_skills__': 'character_skills',
  '!!stompies_tmb_items_effects__': 'effects',
  '!!stompies_tmb_items_unit_abilities__': 'unit_abilities',
  '!!stompies_vmp_items_ancillaries__': 'ancillaries',
  '!!stompies_vmp_items_character_skills__': 'character_skills',
  '!!stompies_vmp_items_effects__': 'effects',
  '!!stompies_vmp_items_unit_abilities__': 'unit_abilities',
  '!!stompies_wef_items_ancillaries__': 'ancillaries',
  '!!stompies_wef_items_character_skills__': 'character_skills',
  '!!stompies_wef_items_effects__': 'effects',
  '!!stompies_wef_items_unit_abilities__': 'unit_abilities',
  '!!stompies_z_unit_abilities_additional_ui_effects__': 'unit_abilities_additional_ui_effects',
};

export { artefacts2DbList, artefacts2LocList, artefacts2LocMap };
