const v2DbList = [
  'character_skill_node_sets_tables',
  'character_skills_tables',
  'character_skill_level_details_tables',
  'character_skill_nodes_tables',
  'character_skill_node_links_tables',
  'character_skill_nodes_skill_locks_tables',
  'effects_tables',
  'character_skill_level_to_effects_junctions_tables',
  'ancillary_to_effects_tables',
  'ancillaries_tables',
  'character_skill_level_to_ancillaries_junctions_tables',
  'character_skills_to_quest_ancillaries_tables',
  'faction_agent_permitted_subtypes_tables',
  'factions_tables',
  'cultures_subcultures_tables',
  'cultures_tables',
  'unit_attributes_tables',
  'special_ability_phase_attribute_effects_tables',
  'special_ability_phase_stat_effects_tables',
  'special_ability_phases_tables',
  'special_ability_to_special_ability_phase_junctions_tables',
  'unit_special_abilities_tables',
  'unit_ability_types_tables',
  'unit_abilities_additional_ui_effects_tables',
  'unit_abilities_to_additional_ui_effects_juncs_tables',
  'unit_abilities_tables',
  'effect_bonus_value_unit_ability_junctions_tables',
];

const v2LocList = [
  'character_skills__',
  'effects__',
  'ancillaries__',
  'cultures__',
  'unit_attributes__',
  'unit_stat_localisations__',
  'unit_ability_types__',
  'unit_abilities_additional_ui_effects__',
  'unit_abilities__',
];

export { v2DbList, v2LocList };
