import CleanListInterface from '../../interfaces/CleanListsInterface';

const unit_special_abilities_tables: CleanListInterface = {
  update_targets_every_frame: 'delete',
  assume_specific_behaviour: 'delete',
  clear_current_order: 'delete',
  spawned_unit: 'delete',
  wind_up_stance: 'delete',
  targetting_aoe: 'delete',
  passive_aoe: 'delete',
  active_aoe: 'delete',
  activation_effect: 'delete',
  miscast_explosion: 'delete',
  ai_usage: 'delete',
  audio: 'delete',
  special_ability_display: 'delete',
  voiceover_state: 'delete',
  additional_melee_cp: 'delete',
  additional_missile_cp: 'delete',
  parent_ability: 'delete',
  spawn_type: 'delete',
  spawn_proxy_vfx: 'delete',
  target_ground_under_allies: 'delete',
  target_ground_under_enemies: 'delete',
  miscast_global_bonus: 'delete',
  composite_scene_group_on_wind_up: 'delete',
  composite_scene_group_on_active: 'delete',
  spawn_is_transformation: 'delete',
  wind_down_stance: 'delete',
  use_loop_stance: 'delete',
  spawn_is_decoy: 'delete',
  only_affect_owned_units: 'delete',
  ability_available_ui_event: 'delete',
  unique_id: 'delete',
  affect_self: 'delete',
  passive: 'delete',

  only_affect_target: 'delete',
  always_affect_self: 'delete',
  unit_position_offset: 'delete',
  update_phase_by_ability_duration: 'delete',
  formation: 'delete',
  behaviour: 'delete',
  audio_switch_override: 'delete',
  current_mana_moves_to_reserve: 'delete',
  spawn_shares_health_and_fatigue: 'delete',
  affect_siege_equipment: 'delete',
  intensity_based_activation: 'delete',
  autoresolver_usage: 'delete',
  autoresolve_cp_multiplier: 'delete',
  autoresolver_targets: 'delete',
  display_stops_when_display_expires: 'delete',
  can_be_copied_to_transformation_unit: 'delete',

  audio_switch_casting_override: 'delete',
  ai_usage_template_group: 'delete',
};

export default unit_special_abilities_tables;
