const ancillariesPrune = [
  'applies_to',
  'transferrable',
  'unique_to_world',
  'unique_to_faction',
  'precedence',
  'start_date',
  'end_date',
  'avatar_skill',
  'avatar_special_ability',
  'legendary_item',
  'mp_exclusive',
  'is_wife_ancillary',
  'category',
  'min_starting_age',
  'max_starting_age',
  'min_expiry_age',
  'max_expiry_age',
  'immortal',
  'provided_bodyguard_unit',
  'provided_banner',
  'uniqueness_score',
  'turns_before_swap_allowed',
  'subcategory',
  'randomly_dropped',
  'can_be_stolen',
  'can_be_destroyed',

  'faction_set',
];

export default ancillariesPrune;
