const unitSpecialAbilitiesPrune = [
  'update_targets_every_frame',
  'assume_specific_behaviour',
  'clear_current_order',
  'spawned_unit',
  'wind_up_stance',
  'targetting_aoe',
  'passive_aoe',
  'active_aoe',
  'activation_effect',
  'miscast_explosion',
  'ai_usage',
  'audio',
  'special_ability_display',
  'voiceover_state',
  'additional_melee_cp',
  'additional_missile_cp',
  'parent_ability',
  'spawn_type',
  'spawn_proxy_vfx',
  'target_ground_under_allies',
  'target_ground_under_enemies',
  'miscast_global_bonus',
  'composite_scene_group_on_wind_up',
  'composite_scene_group_on_active',
  'spawn_is_transformation',
  'wind_down_stance',
  'use_loop_stance',
  'spawn_is_decoy',
  'only_affect_owned_units',
  'ability_available_ui_event',
  'unique_id',
  'affect_self',
  'passive',

  'only_affect_target',
  'always_affect_self',
  'unit_position_offset',
  'update_phase_by_ability_duration',
  'formation',
  'behaviour',
  'audio_switch_override',
  'current_mana_moves_to_reserve',
  'spawn_shares_health_and_fatigue',
  'affect_siege_equipment',
  'intensity_based_activation',
  'autoresolver_usage',
  'autoresolve_cp_multiplier',
  'autoresolver_targets',
  'display_stops_when_display_expires',
  'can_be_copied_to_transformation_unit',

  'audio_switch_casting_override',
  'ai_usage_template_group',

  'mom_vortex_key',
  'align_orientation_to_target_unit',
];

export default unitSpecialAbilitiesPrune;
